"""
MassOpenCloud / Hardware Isolation Layer (HIL)

HIL Slurm Constants

June 2017, Tim Donahue	tpd001@gmail.com
"""

SHOW_OBJ_TIME_FMT = '%Y-%m-%dT%H:%M:%S'
RES_CREATE_TIME_FMT = SHOW_OBJ_TIME_FMT

SHOW_PARTITION_MAXTIME_HMS_FMT = '-%H:%M:%S'

RES_NAME_TIME_FMT = '%Y%m%d_%H%M%S'

RES_CREATE_HIL_FEATURES='HIL'

RES_CREATE_FLAGS = 'MAINT,IGNORE_JOBS'
# RES_RELEASE_FLAGS = '-MAINT'


HIL_RESERVE = 'reserve'
HIL_RELEASE = 'release'

HIL_RESERVATION_OPERATIONS = [HIL_RESERVE, HIL_RELEASE]
HIL_RESERVATION_COMMANDS = ['hil_%s' % op for op in HIL_RESERVATION_OPERATIONS]

HIL_RESNAME_PREFIX = 'flexalloc_MOC_'
HIL_RESNAME_FIELD_SEPARATOR = '_'


# EOF
